services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  couchdb-init:
    image: curlimages/curl:8.8.0
    depends_on:
      couchdb:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Init CouchDB...' &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_users >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_replicator >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_global_changes >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/groups >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -H 'Content-Type: application/json' -X PUT http://couchdb:5984/_node/_local/_config/log/level -d '\"error\"' >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -H 'Content-Type: application/json' -X PUT http://couchdb:5984/_node/_local/_config/search/enabled -d '\"false\"' >/dev/null || true &&
        curl -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X DELETE http://couchdb:5984/_node/_local/_config/search/clouseau_nodes >/dev/null || true &&
        echo 'Init done.'
      "
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alternating-care-be
    env_file:
      - .env
    environment:
      - COUCHDB_URL=http://couchdb:5984
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      couchdb:
        condition: service_healthy
      couchdb-init:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  couchdb-data:
